### ISSUE TITLE
Fenrir - Natural Weapons (wolf) reduced damage even though no damage was dealt

### ISSUE THREAD

**Issue by origamiswami** [DrakoGlyph/Riverport#11]
Fenrir was in wolf form with Natural Weapons and The Pale Moon Pendant in play. Osiris made Fenrir deal 1 psychic damage to himself, which was reduced to 0 by the Pendant, but it still applied the damage reduction effect to Fenrir. The same thing happened with the damage caused by Jump Scare.

**Comment by DrakoGlyph** [comment]
Just a simple check to add in, silly me
