### ISSUE TITLE
DragonTamer - Jormungander can destroy environment cards under himself?

### ISSUE THREAD

**Issue by origamiswami** [DrakoGlyph/Riverport#13]
For the "destroy an environment card" part of Jormungander's power, it lets you choose an environment card underneath Jormungander. Is this intended behavior? Seems weird to destroy a card under a dragon in order to destroy another card under the same dragon. This probably means that other things that destroy environment cards will destroy cards under dragons as well, not sure if that's intended as well or not.

**Comment by DrakoGlyph** [comment]
Jormungander, and all the Dragons, are getting a rework tomorrow, actually.
But this is an odd case of a card's UnderLocation being considered "In Play".
