### ISSUE TITLE
DragonTamer - Tortuga did not prevent damage to Dragon Tamer

### ISSUE THREAD

**Issue by origamiswami** [DrakoGlyph/Riverport#17]
Tried to use Tortuga to prevent damage to Dragon Tamer from The Zorrm. It removed a card from under Tortuga, but then damage was dealt anyway

**Comment by DrakoGlyph** [comment]
AS of the Dragontamer Dragon Consistency Rework, this is no longer relevant, though I'm not sure why it didn't work.
