### ISSUE TITLE
Weaver - Read the Weave choice dialogue wording is confusing

### ISSUE THREAD

**Issue by origamiswami** [DrakoGlyph/Riverport#18]
The card functions correctly, but the choice dialog made me think I was choosing the card to end up on top of the deck, rather than the first card to be put on top that will then be covered by the other card. It would be more intuitive to ask "Which card do you want to end up on top of the deck" or something to that effect, since that's what the player is most concerned with.

**Comment by DrakoGlyph** [comment]
We actually don't get much influence over what the dialog says, actually.

**Comment by DrakoGlyph** [comment]
Though, I did find the method I was looking for, comically thanks to you mentioning DW Nightmist ^^
