### ISSUE TITLE
DragonTamer - Learning Experience wording

### ISSUE THREAD

**Issue by origamiswami** [DrakoGlyph/Riverport#20]
I noticed that it asks if you want to put a card under a dragon before the draw actually happens. If this is correct, it should probably say "...when you draw a card, you may first put a card in your hand under a dragon." If it should trigger after the card draw, letting the player put the drawn card under a dragon, then it should probably say "...when you draw a card, you may then put a card in your hand under a dragon". Just to make the effect clear.

**Comment by DrakoGlyph** [comment]
Triggers are hard @-@
