### ISSUE TITLE
Once Again Labs - The Raptor dealt too much damage

### ISSUE THREAD

**Issue by origamiswami** [DrakoGlyph/Riverport#6]
The Raptor dealt 4 damage, when it was the only dragon in play. (I wasn't using Dragon Tamer, so there weren't any hero dragons in play)

**Comment by DrakoGlyph** [comment]
I'm guessing I forgot the "IsInPlayAndHasRuleText" check

**Comment by DrakoGlyph** [comment]
Confirmed.
