### ISSUE TITLE
Fenrir - Natural Weapons (human) turn continues while dialog is up

### ISSUE THREAD

**Issue by origamiswami** [DrakoGlyph/Riverport#9]
After using the power in human form, the turn continues with Fenrir drawing a card and moving to the next turn in the turn order, all while the dialogue for choosing a hero to draw a card is still onscreen. Fenrir was the last hero in the lineup, so it started going through the environment turn before I had made a selection for Natural Weapons.

**Comment by DrakoGlyph** [comment]
So you're gonna laugh (if you even read these) but I found this bug in Playtesting (And Called it Natural Weapons doesn't Yield)
Then forgot about it because I don't tend to use the power on this card.
And guess what the problem was? Not having the keyword "yield" in my code
